Overhaul CI to add coverage
This runs the check task on the root project (sans tests we run elsewhere) which should start catching everything. It removes apiCheck from the platform test shards as that requires building all targets, so they should get faster and work on Windows.

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -10,7 +10,7 @@ on:
       - '**'
 
 env:
-  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
+  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.logging.stacktrace=full"
 
 jobs:
   zig:
@@ -44,9 +44,7 @@ jobs:
             task: macosArm64Test
           - os: ubuntu-latest
             task: linuxX64Test
-
     runs-on: ${{ matrix.platform.os }}
-
     steps:
       - uses: actions/checkout@v5
       - uses: actions/setup-java@v5
@@ -59,7 +57,7 @@ jobs:
           name: jni-binaries
           path: zipline/src/jvmMain/resources/jni
 
-      - run: ./gradlew jvmTest ${{ matrix.platform.task }} apiCheck --stacktrace
+      - run: ./gradlew jvmTest ${{ matrix.platform.task }}
 
       - uses: actions/upload-artifact@v4
         if: ${{ always() }}
@@ -68,11 +66,29 @@ jobs:
           path: '**/build/reports/tests/**'
           retention-days: 1
 
-  samples:
+  simulator-tests:
+    needs:
+      - zig
+    runs-on: macos-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        platform:
+          - task: iosSimulatorArm64Test
+          - task: tvosSimulatorArm64Test
+    steps:
+      - uses: actions/checkout@v5
+      - uses: actions/setup-java@v5
+        with:
+          distribution: 'zulu'
+          java-version-file: .github/workflows/.java-version
+
+      - run: ./gradlew ${{ matrix.platform.task }}
+
+  check:
     runs-on: macos-latest
     needs:
       - zig
-
     steps:
       - uses: actions/checkout@v5
       - uses: actions/setup-java@v5
@@ -85,7 +101,37 @@ jobs:
           name: jni-binaries
           path: zipline/src/jvmMain/resources/jni
 
-      - run: ./gradlew -p samples check --stacktrace
+      # Disable jvmTest and native tests because they're run in platform-tests and simulator-tests.
+      - run: >
+          ./gradlew
+          check
+          -x allTests
+          -x iosSimulatorArm64Test
+          -x iosX64Test
+          -x jvmTest
+          -x linuxX64Test
+          -x macosArm64Test
+          -x macosX64Test
+          -x tvosSimulatorArm64Test
+          -x tvosX64Test
+
+  sample-check:
+    runs-on: macos-latest
+    needs:
+      - zig
+    steps:
+      - uses: actions/checkout@v5
+      - uses: actions/setup-java@v5
+        with:
+          distribution: 'zulu'
+          java-version-file: .github/workflows/.java-version
+
+      - uses: actions/download-artifact@v5
+        with:
+          name: jni-binaries
+          path: zipline/src/jvmMain/resources/jni
+
+      - run: ./gradlew -p samples check
 
   android-tests:
     runs-on: ubuntu-latest
@@ -127,14 +173,30 @@ jobs:
           pod install
           xcodebuild -workspace WorldClock.xcworkspace -scheme WorldClock -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest'
 
-  build:
-    runs-on: macos-latest
+  final-status:
+    if: ${{ !cancelled() }}
+    runs-on: ubuntu-latest
     needs:
       - platform-tests
-      - samples
+      - simulator-tests
+      - check
+      - sample-check
       - android-tests
       - ios-app
+    steps:
+      - name: Check
+        run: |
+          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
+          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
+            echo "One or more required jobs failed"
+            exit 1
+          fi
 
+  publish:
+    if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'cashapp/zipline' }}
+    runs-on: macos-latest
+    needs:
+      - final-status
     steps:
       - uses: actions/checkout@v5
       - uses: actions/setup-java@v5
@@ -147,25 +209,14 @@ jobs:
           name: jni-binaries
           path: zipline/src/jvmMain/resources/jni
 
-      - run: ./gradlew assemble :dokkaHtmlMultiModule
+      - run: ./gradlew publishToMavenCentral
+        env:
+          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_CENTRAL_USERNAME }}
+          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_CENTRAL_PASSWORD }}
+          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SECRET_KEY }}
+          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_SECRET_PASSPHRASE }}
 
-      - uses: actions/upload-artifact@v4
-        with:
-          name: zipline-jvm.jar
-          path: zipline/build/libs/zipline-jvm-*.jar
-          if-no-files-found: error
-
-      - uses: actions/upload-artifact@v4
-        with:
-          name: zipline-android.aar
-          path: zipline/build/outputs/aar/*-release.aar
-          if-no-files-found: error
-
-      - uses: actions/upload-artifact@v4
-        with:
-          name: zipline-cli.zip
-          path: zipline-cli/build/distributions/zipline-cli-*.zip
-          if-no-files-found: error
+      - run: ./gradlew :dokkaHtmlMultiModule
 
       - uses: actions/upload-artifact@v4
         with:
@@ -173,16 +224,7 @@ jobs:
           path: build/dokka/htmlMultiModule/
           if-no-files-found: error
 
-      - run: ./gradlew publishToMavenCentral
-        if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'cashapp/zipline' }}
-        env:
-          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_CENTRAL_USERNAME }}
-          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_CENTRAL_PASSWORD }}
-          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SECRET_KEY }}
-          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_SECRET_PASSPHRASE }}
-
       - name: Deploy docs to website
-        if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'cashapp/zipline' }}
         uses: JamesIves/github-pages-deploy-action@releases/v3
         with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
